---
# IMPORTANT: Change settings here, but DO NOT change the spacing.
# Remove comments and add values where applicable.
# The descriptions below should be self-explanatory

title: "Helping You Write Academic Papers in R using Texevier"
#subtitle: "This will appear as Right Header"

documentclass: "elsarticle"

# --------- Thesis title (Optional - set to FALSE by default).
# You can move the details below around as you please.
Thesis_FP: FALSE
# Entry1: "An unbelievable study with a title spanning multiple lines."
# Entry2: "\\textbf{Nico Katzke}" # textbf for bold
# Entry3: "A thesis submitted toward the degree of Doctor of Philosophy"
# Uni_Logo: Tex/Logo.png # Place a logo in the indicated location (from your root, e.g. defaults to ~/Tex/Logo.png) and uncomment this line. Leave uncommented for no image
# Logo_width: 0.3 # If using a logo - use this to set width (size) of image
# Entry4: "Under the supervision of: \\vfill Prof. Joe Smith and Dr. Frank Smith"
# Entry5: "Stellenbosch University"
# Entry6: April 2020
# Entry7:
# Entry8:

# --------- Front Page
# Comment: ----- Follow this pattern for up to 5 authors
AddTitle: TRUE # Use FALSE when submitting to peer reviewed platform. This will remove author names.
Author1: "Nico Katzke^[__Contributions:__  \\newline _The authors would like to thank no institution for money donated to this project. Thank you sincerely._]"  # First Author - note the thanks message displayed as an italic footnote of first page.
Ref1: "Prescient Securities, Cape Town, South Africa" # First Author's Affiliation
Email1: "nfkatzke\\@gmail.com" # First Author's Email address

Author2: "John Smith"
Ref2: "Some other Institution, Cape Town, South Africa"
Email2: "John\\@gmail.com"
CommonAffiliation_12: TRUE # If Author 1 and 2 have a common affiliation. Works with _13, _23, etc.

Author3: "John Doe"
Email3: "Joe\\@gmail.com"

CorrespAuthor_1: TRUE  # If corresponding author is author 3, e.g., use CorrespAuthor_3: TRUE

# Comment out below to remove both. JEL Codes only given if keywords also given.
keywords: "Multivariate GARCH \\sep Kalman Filter \\sep Copula" # Use \\sep to separate
JELCodes: "L250 \\sep L100"

# ----- Manage headers and footers:
#BottomLFooter: $Title$
#BottomCFooter:
#TopLHeader: \leftmark # Adds section name at topleft. Remove comment to add it.
BottomRFooter: "\\footnotesize Page \\thepage" # Add a '#' before this line to remove footer.
addtoprule: TRUE
addfootrule: TRUE               # Use if footers added. Add '#' to remove line.

# --------- page margins:
margin: 2.3 # Sides
bottom: 2 # bottom
top: 2.5 # Top
HardSet_layout: TRUE # Hard-set the spacing of words in your document. This will stop LaTeX squashing text to fit on pages, e.g.
# This is done by hard-setting the spacing dimensions. Set to FALSE if you want LaTeX to optimize this for your paper.

# --------- Line numbers
linenumbers: FALSE # Used when submitting to journal

# ---------- References settings:
# You can download cls format here: https://www.zotero.org/ - simply search for your institution. You can also edit and save cls formats here: https://editor.citationstyles.org/about/
# Hit download, store it in Tex/ folder, and change reference below - easy.
bibliography: Tex/ref.bib       # Do not edit: Keep this naming convention and location.
csl: Tex/harvard-stellenbosch-university.csl # referencing format used.
# By default, the bibliography only displays the cited references. If you want to change this, you can comment out one of the following:
#nocite: '@*' # Add all items in bibliography, whether cited or not
# nocite: |  # add specific references that aren't cited
#  @grinold2000
#  @Someoneelse2010

# ---------- General:
RemovePreprintSubmittedTo: TRUE  # Removes the 'preprint submitted to...' at bottom of titlepage
Journal: "Journal of Finance"   # Journal that the paper will be submitting to, if RemovePreprintSubmittedTo is set to TRUE.
toc: FALSE                       # Add a table of contents
numbersections: TRUE             # Should sections (and thus figures and tables) be numbered?
fontsize: 11pt                  # Set fontsize
linestretch: 1.2                # Set distance between lines.
link-citations: TRUE            # This creates dynamic links to the papers in reference list.

### Adding additional latex packages:
# header-includes:
#    - \usepackage{colortbl} # Add additional packages here.

output:
  pdf_document:
    keep_tex: TRUE
    template: Tex/TexDefault.txt
    fig_width: 3.5 # Adjust default figure sizes. This can also be done in the chunks of the text.
    fig_height: 3.5
abstract: |
  Abstract to be written here. The abstract should not be too long and should provide the reader with a good understanding what you are writing about. Academic papers are not like novels where you keep the reader in suspense. To be effective in getting others to read your paper, be as open and concise about your findings here as possible. Ideally, upon reading your abstract, the reader should feel he / she must read your paper in entirety.
---

<!-- First: Set your default preferences for chunk options: -->

<!-- If you want a chunk's code to be printed, set echo = TRUE. message = FALSE stops R printing ugly package loading details in your final paper too. I also suggest setting warning = FALSE and checking for warnings in R, else you might find ugly warnings in your paper. -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')

if(!require("tidyverse")) install.packages("tidyverse")

pacman::p_load("MTS", "robustbase")

pacman::p_load("tidyverse", "devtools", "rugarch", "rmgarch", 
     "forecast", "tbl2xts", "lubridate", "PerformanceAnalytics", 
     "ggthemes", "dplyr", "cowplot", "fmxdat") 

list.files('C:/Users/Cabous/OneDrive/Desktop/22017542_Exam/code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))
```


# Question 5

```{r}
# Load Data

cncy <- read_rds("data/currencies.rds")

cncy_Carry <- read_rds("data/cncy_Carry.rds")

cncy_value <- read_rds("data/cncy_value.rds")

cncyIV <- read_rds("data/cncyIV.rds")

bbdxy <- read_rds("data/bbdxy.rds")

```


# Volatility

```{r}
## To analyse whether the Rand is volatile lets look at Implied volatility
# What cuurencies are in the data?

cncyIV %>% group_by(Name) %>% pull(Name) %>% unique 
```

```{r}
IV_plot <- cncyIV %>% 
    
    filter(Name==c("China_IV", "India_IV", "SouthAfrica_IV",
                   "UK_IV", "EU_IV", "Singapore_IV")) %>%
    
    filter(date > as.Date("1999-12-31")) %>% 
    
    group_by(date) %>%
    
    ggplot() + 
    
    geom_line(aes(x=date, y=Price, color=Name)) +
    
    theme_bw() +  
    
    labs(x = "Dates", y = "Price (relative to USD)",
         
         title = "Implied Volatility ", subtitle = "",
         
         caption = "Note:\nOwn Calculations") +
    
    guides(col=guide_legend("Currency"))

IV_plot
```

This suggests that the market foresees the highest future volatility for the Rand, for this sub-sample.


```{r}


# Calculating Returns and Cleaning

zar_rtn <- cncy %>% 
    
    arrange(date) %>% 
    
    filter(date > as.Date("1999-12-31")) %>% 
    
    filter(Name %in% "SouthAfrica_Cncy") %>% 
    
    mutate(Price = na.locf(Price)) %>% 
    
    mutate(dlogret = log(Price) - log(lag(Price))) %>% 
    
    mutate(scaledret = (dlogret - mean(dlogret, na.rm = T))) %>% 
    
    filter(date > dplyr::first(date)) 

xts_zar_rtn <- zar_rtn %>% 
    
    tbl_xts(., cols_to_xts = "dlogret", spread_by = "Name")

MarchTest(xts_zar_rtn)
```


```{r}
xts_zar_rtn[is.na(xts_zar_rtn)] <- 0

PlotRtn = cbind(xts_zar_rtn, xts_zar_rtn^2, abs(xts_zar_rtn))

colnames(PlotRtn) = c("Returns", "Returns_Sqd", "Returns_Abs")

PlotRtn <- PlotRtn %>% 
    
    xts_tbl() %>%
    
    gather(ReturnType, Returns, -date) 

# Plot

ggplot(PlotRtn) + 
    
    geom_line(aes(x = date, y = Returns, colour = ReturnType, alpha = 0.5)) + 
    
    ggtitle("Return Type Persistence: USD/ZAR") + 
    
    facet_wrap(~ReturnType, nrow = 3, ncol = 1, scales = "free") + 
    
    guides(alpha = "none", colour = "none") + 
    
    fmxdat::theme_fmx()


```

```{r}
forecast::Acf(xts_zar_rtn, main = "ACF: Equally Weighted Return")
```

```{r}
forecast::Acf(xts_zar_rtn^2, main = "ACF: Squared Equally Weighted Return")
```

```{r}
forecast::Acf(abs(xts_zar_rtn), main = "ACF: Absolute Equally Weighted Return")
```

```{r}
Box.test(coredata(xts_zar_rtn^2), type = "Ljung-Box", lag = 12)
```

# Find best model

```{r}

best_model <- Vol_Model_Sel(zar_rtn)

best_model
```

# Fit Model

```{r}

garch_fit_gjrGARCH <- vol_func(zar_rtn, "gjrGARCH")

garch_fit_sGARCH <- vol_func(zar_rtn, "sGARCH")

signbias(garch_fit_sGARCH)
```

```{r, results = 'asis'}

pacman::p_load(xtable)
Table <- xtable(garch_fit_sGARCH@fit$matcoef)

print(Table, type = "latex", comment = FALSE)
```

```{r}
#Conditional variance Plot

persistence(garch_fit_sGARCH)
```

```{r}
# Persistence is alpha + beta, and it is typically very high and close to 1

# To view the conditional variance plot, use:
sigma <- sigma(garch_fit_sGARCH) %>% 
    
    xts_tbl() 

colnames(sigma) <- c("date", "sigma") 

sigma <- sigma %>% 
    
    mutate(date = as.Date(date))

Con_var_plot <- 
  
ggplot() + 
    
  geom_line(data = PlotRtn %>% filter(ReturnType == "Returns_Sqd") %>% 
                
                select(date, Returns) %>% 
              
              unique %>% mutate(Returns = sqrt(Returns)), 
            
            aes(x = date, y = Returns)) + 
  
  geom_line(data = sigma, aes(x = date, y = sigma), 
            color = "red", size = 2, alpha = 0.8) + 
  
  
  labs(title = "Comparison: Returns Sigma vs Sigma from Garch", 
       
       subtitle = "Note the smoothing effect of garch, as noise is controlled for.", x = "", y = "Comparison of estimated volatility",
       
       caption = "Source: Fin metrics class | Calculations: Own") + 
  
    fmxdat::theme_fmx(CustomCaption = TRUE)


fmxdat::finplot(Con_var_plot, y.pct = T, y.pct_acc = 1)

```

```{r}
news_plot <- newsimpact(z = NULL, garch_fit_sGARCH)

plot(news_plot$zx, news_plot$zy, ylab = news_plot$yexpr, xlab = news_plot$xexpr, type = "l", 
    main = "News Impact Curve")
```

```{r}

plot(garch_fit_sGARCH, which = "all")
```


```{r}
# Lets investigate further
# lets compare Smoothed ZAR Vol to mean Global VOL

# Calculate Mean Global VOL

mean_Gvol <- cncyIV %>% 
    
    filter(date > as.Date("1999-12-31")) %>% 
    
    group_by(date) %>% 
    
    summarise(mean_vol = mean(Price)) %>% 
    
    mutate(Global_vol = mean_vol/max(mean_vol))

# Wrangle Sigma 

sigma <- sigma %>% 
    
    mutate(Date = as.Date(date)) %>% 
    
    mutate(ZAR_sigma = sigma/max(sigma))%>%
    
    left_join(., mean_Gvol, by = "date")

# Plot 

Vol_compare_plot <- sigma %>% 
    
    select(-date) %>% 
    
    pivot_longer(c("ZAR_sigma", "Global_vol"), 
                 names_to = "Vol_type", 
                 values_to = "VOL") %>%
    
    ggplot() +
    
    geom_line(aes(Date, VOL, colour = Vol_type)) +
    
    labs(title = "ZAR Volatility and Mean Currency Volatility",
         x = "", 
         y = "Proprotion of Max Vol") +
    
    fmx_cols() +
    
    theme_fmx(title.size = ggpts(25)) 

finplot(Vol_compare_plot)

```



















\newpage

# References {-}

<div id="refs"></div>


# Appendix {-}

## Appendix A {-}

Some appendix information here

## Appendix B {-}

